export function Methodology() {
  return (
    <div className="w-full max-w-4xl mx-auto p-6 md:p-10 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <h2 className="font-heading text-4xl text-espresso mb-6">
        Methodology & Sources
      </h2>

      {/* Disclaimer Box */}
      <div className="bg-pink/5 border-l-4 border-pink p-6 rounded-r-2xl mb-10 shadow-sm">
        <p className="font-body italic text-espresso/90 leading-relaxed">
          "Any of the content within Sanghay Laya including protocols on safety and healthy and medical summaries are NOT generated by AI nor are they personal opinions of the developers. All data presented are within the highest standard of objectivity and safety, to do that our method is to make sure 100% of the statistical and medical data in this website is DIRECTLY sourced and synthesized from peer-reviewed medical journal research papers, and globally recognized clinical guidelines like WPATH and UCSF, official government agencies like FDA and NIH, etc. This strictness guarantees that you may only receive authoritative and evidence-based information for your own health and well being."
        </p>
      </div>

      {/* Citations Section */}
      <div className="space-y-10">
        <section>
          <h3 className="font-heading text-xl text-espresso mb-4 font-bold">I. Clinical Guidelines & Medical Safety</h3>
          <ul className="space-y-4 text-sm text-espresso/80 font-body">
            <li className="pl-6 -indent-6">
              Endocrine Society. (2017). Endocrine treatment of gender-dysphoric/gender-incongruent persons: An Endocrine Society clinical practice guideline. The Journal of Clinical Endocrinology & Metabolism. <a href="https://academic.oup.com/jcem/article/102/11/3869/4157558" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://academic.oup.com/jcem/article/102/11/3869/4157558</a>
            </li>
            <li className="pl-6 -indent-6">
              National Institutes of Health (NIH) / MedlinePlus. (n.d.). Spironolactone. U.S. National Library of Medicine. <a href="https://medlineplus.gov/druginfo/meds/a682627.html" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://medlineplus.gov/druginfo/meds/a682627.html</a>
            </li>
            <li className="pl-6 -indent-6">
              U.S. Food and Drug Administration (FDA). (2017). FDA warns about illegal use of injectable silicone for body contouring and associated health risks. <a href="https://www.fda.gov/news-events/press-announcements/fda-warns-about-illegal-use-injectable-silicone-body-contouring-and-associated-health-risks" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://www.fda.gov/news-events/press-announcements/fda-warns-about-illegal-use-injectable-silicone-body-contouring-and-associated-health-risks</a>
            </li>
            <li className="pl-6 -indent-6">
              UCSF Gender Affirming Health Program. (n.d.). Bone health and osteoporosis. <a href="https://transcare.ucsf.edu/guidelines/bone-health-and-osteoporosis" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://transcare.ucsf.edu/guidelines/bone-health-and-osteoporosis</a>
            </li>
            <li className="pl-6 -indent-6">
              World Professional Association for Transgender Health (WPATH). (2022). Standards of care for the health of transgender and gender diverse people, version 8. <a href="https://www.wpath.org/publications/soc" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://www.wpath.org/publications/soc</a>
            </li>
          </ul>
        </section>

        <section>
          <h3 className="font-heading text-xl text-espresso mb-4 font-bold">II. Peer-Reviewed Research & Academic Journals</h3>
          <ul className="space-y-4 text-sm text-espresso/80 font-body">
            <li className="pl-6 -indent-6">
              Bustos, S. S., Murray, H. B., & et al. (2021). Regret after gender-affirmation surgery: A systematic review and meta-analysis of prevalence. Plastic and Reconstructive Surgery – Global Open. <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8099405/" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8099405/</a>
            </li>
            <li className="pl-6 -indent-6">
              Shatzel, A., & et al. (2023). The importance of safely prescribing hormones in the transgender community. National Library of Medicine. <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC10548402/" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://pmc.ncbi.nlm.nih.gov/articles/PMC10548402/</a>
            </li>
          </ul>
        </section>

        <section>
          <h3 className="font-heading text-xl text-espresso mb-4 font-bold">III. Psychological, Social, & Civil Rights Data</h3>
          <ul className="space-y-4 text-sm text-espresso/80 font-body">
            <li className="pl-6 -indent-6">
              American Civil Liberties Union (ACLU). (n.d.). Four myths about trans athletes, debunked. <a href="https://www.aclu.org/news/lgbtq-rights/four-myths-about-trans-athletes-debunked" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://www.aclu.org/news/lgbtq-rights/four-myths-about-trans-athletes-debunked</a>
            </li>
            <li className="pl-6 -indent-6">
              American Psychological Association (APA). (n.d.). Gender-affirmative care. <a href="https://www.apa.org/topics/lgbtq/gender-affirmative-care" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://www.apa.org/topics/lgbtq/gender-affirmative-care</a>
            </li>
            <li className="pl-6 -indent-6">
              GLAAD & Movement Advancement Project (MAP). (n.d.). Fact sheet: Misleading narratives about transgender people and restrooms. <a href="https://glaad.org/fact-sheet-misleading-narratives-about-transgender-people-and-restrooms-locker-rooms-and-other-single-sex-spaces/" target="_blank" rel="noopener noreferrer" className="text-pink hover:underline break-all">https://glaad.org/fact-sheet-misleading-narratives-about-transgender-people-and-restrooms-locker-rooms-and-other-single-sex-spaces/</a>
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
}
